accelerator: cuda:0
cfg_file: /home/RUS_CIP/st186731/research_project/hybrid_approach/config_yaml/ddacs-node-regression.yaml
dataset:
  dir: /mnt/data/jiang
  edge_encoder: true
  edge_encoder_bn: false
  edge_encoder_name: EdgeCentrality
  format: PyG-DDACSNPYStream
  max_samples: null
  name: node-regression
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: DegreeCentrality
  task: graph
  task_type: regression
  transductive: false
device: cuda:0
gnn:
  dim_edge: 64
  dim_inner: 64
  dim_out: 3
  head: inductive_node
  layers_post_mp: 3
gt:
  attn:
    signed_sqrt: true
  attn_dropout: 0.1
  dropout: 0.1
  layer_type: GritTransformer
  n_heads: 2
metric_agg: argmin
metric_best: mae
model:
  laplace_lambda: 0.05
  laplace_norm_mode: per_node
  laplace_normalized: true
  laplace_on_residuals: true
  loss_fun: mse_combined_with_laplacian
  only_mse: false
  type: GritTransformer
optim:
  base_lr: 0.0005
  clip_grad_norm: true
  max_epoch: 5
  num_warmup_epochs: 5
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 0.0001
out_dir: results/ddacs-node-regression
params: 222915
run_dir: results/ddacs-node-regression/41
run_id: 41
seed: 41
share:
  num_splits: 3
train:
  batch_size: 8
  eval_period: 1
  mode: train
work_dir: /home/RUS_CIP/st186731/research_project/hybrid_approach/grit_like_and_graphormer_like
