out_dir: results
metric_best: mae
metric_agg: argmin
accelerator: "cuda:0"
tensorboard_each_run: True

dataset:
  format: PyG-DDACSNPYStream      # your NPY stream
  name: node-regression
  dir: /mnt/data/jiang
  task: graph
  split_mode: standard
  task_type: regression
  transductive: False
  # node features: 34-D → project inside backbone; we still add centrality
  node_encoder: True
  node_encoder_name: GraphormerCentrality
  node_encoder_bn: False
  edge_encoder: False              # Graphormer uses attention bias instead
  max_samples: 256
  max_nodes: 2048                  # pad/truncate per batch
  graphormer:
    max_dist: 32                   # SPD cutoff
    num_edge_types: 0              # set >0 if you pass edge types

train:
  mode: example
  batch_size: 8
  eval_period: 1
  ckpt_best: True
  ckpt_clean: True

model:
  type: GraphormerBackbone         # registered @register_network
  loss_fun: mse
  graph_pooling: none

# Graphormer backbone hyperparams (must match your class signature)
graphormer:
  dim_in: 34                       # raw node feature dim
  dim_hidden: 256
  dim_out: 3
  num_layers: 6
  num_heads: 8
  dropout: 0.1
  attn_dropout: 0.1
  use_cls_token: False

gnn:
  head: node
  layers_pre_mp: 0
  layers_post_mp: 0                # backbone already handles the stack
  dim_inner: 256
  dim_out: 3
  batchnorm: False                 # LayerNorm is used inside backbone
  act: relu
  dropout: 0.0

optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 2.0e-4
  max_epoch: 10
  scheduler: linear_with_warmup
  num_warmup_epochs: 3
